canvas = document.getElementById("oli");
color = "blue";
ctx = canvas.getContext("2d");
ctx.beginPath();
ctx.strokeStyle = color;
ctx.lineWidth = 7;
ctx.arc(250, 210, 40, 0, 2 * Math.PI);
ctx.stroke();
canvas = document.getElementById("oli");
color = "yellow";
ctx = canvas.getContext("2d");
ctx.beginPath();
ctx.strokeStyle = color;
ctx.lineWidth = 7;
ctx.arc(290, 250, 40, 0, 2 * Math.PI);
ctx.stroke();
canvas = document.getElementById("oli");
color = "black";
ctx = canvas.getContext("2d");
ctx.beginPath();
ctx.strokeStyle = color;
ctx.lineWidth = 7;
ctx.arc(340, 210, 40, 0, 2 * Math.PI);
ctx.stroke();
canvas = document.getElementById("oli");
color = "green";
ctx = canvas.getContext("2d");
ctx.beginPath();
ctx.strokeStyle = color;
ctx.lineWidth = 7;
ctx.arc(380, 250, 40, 0, 2 * Math.PI);
ctx.stroke();
canvas = document.getElementById("oli");
color = "red";
ctx = canvas.getContext("2d");
ctx.beginPath();
ctx.strokeStyle = color;
ctx.lineWidth = 7;
ctx.arc(430, 210, 40, 0, 2 * Math.PI);
ctx.stroke();